version: '3'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6380:6379
    volumes:
      - /root/apps/data/redis:/data
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - /root/apps/data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: ufckRgauWqRwtirmMiNk!!
  master:
    image: mailtester2/engine:master
    container_name: master
    restart: always
    ports:
      - "3101:3000"
    volumes:
      - /root/apps/master_assets:/assets
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_DEBUG=bull
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@mongo:27017/test?authSource=admin
      - REDIS_URL=redis://redis:6379
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "3104:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  dashboard:
    image: mailtester2/engine:dashboard
    container_name: dashboard
    restart: always
    ports:
      - "3103:3000"