version: '3'
services:
  worker1:
    image: mailtester2/engine:worker
    container_name: worker1
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=1
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.192
      - RDNS=ceres.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker2:
    image: mailtester2/engine:worker
    container_name: worker2
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=2
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.193
      - RDNS=pluto.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker3:
    image: mailtester2/engine:worker
    container_name: worker3
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=3
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.194
      - RDNS=eris.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker4:
    image: mailtester2/engine:worker
    container_name: worker4
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=4
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.195
      - RDNS=makemake.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker5:
    image: mailtester2/engine:worker
    container_name: worker5
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=5
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.196
      - RDNS=haumea.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker6:
    image: mailtester2/engine:worker
    container_name: worker6
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=6
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.197
      - RDNS=charon.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker7:
    image: mailtester2/engine:worker
    container_name: worker7
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=7
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.198
      - RDNS=tethys.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
  worker8:
    image: mailtester2/engine:worker
    container_name: worker8
    command: npm run worker
    restart: always
    network_mode: "host"
    environment:
      - NODE_DEBUG=bull
      - RELAY_ID=1
      - TOR_ID=8
      - MONGODB_URI=mongodb://mongo:ufckRgauWqRwtirmMiNk!!@95.216.198.65:27018/test?authSource=admin
      - REDIS_URL=redis://95.216.198.65:6380
      - IP=5.135.197.199
      - RDNS=dione.diversityroianalytics.com
      - SOCKS_PROXY_SERVER=socks5://localhost:9050
      - HEADLESS_HOST=http://localhost:3102
